name: deploy terraform
on: [push]
defaults:
  run:
    working-directory: backend
jobs:
  run_terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_cloudflare_account_id: ${{ secrets.cloudflare_account_id }}
      TF_VAR_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - name: Add profile credentials to ~/.aws/credentials
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile cloud-resume
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile cloud-resume
          aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile cloud-resume
      - name: Test AWS Creds
        run: aws sts get-caller-identity
      - name: export env
        run: |
          export
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        env: 
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS.ACCESS_TOKEN }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS.SECRET_KEY }}
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        env: 
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS.ACCESS_TOKEN }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS.SECRET_KEY }}
        id: plan
        run: terraform plan -no-color
