name: deploy terraform
on: [push]
defaults:
  run:
    working-directory: backend
jobs:
  run_terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_cloudflare_account_id: ${{ secrets.cloudflare_account_id }}
      TF_VAR_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS.ACCESS_TOKEN }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS.SECRET_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: export env
        run: |
          export
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
